### ISSUE TITLE
java2smali

### ISSUE THREAD

**Issue by Praveenprajith** [ManojBhakarPCM/AModStudio3#1]
how to run this ? i want recompile java to smali

**Comment by ManojBhakarPCM** [comment]
this project has no functionality to compile java.
because it would be a huge task(android studio , which is a huge sized program, does that)
what i do when i need to compile java to smali?
i open up androidStudio and make a small app and writes my codes in a class. then i compile. then i convert apk to smali. then i  extract that class.
